#!/usr/bin/env bash
# generate_data.sh — All data is synthetically generated by the experiments.
# No external downloads are required.
set -euo pipefail
echo "All experimental data is generated synthetically by the experiment scripts."
echo "Run scripts/reproduce_all.sh to generate all data and results."
echo "No external datasets are required."
